# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e4233c02be9bf63421a67aeaf6a1ccee862344506d9482308b1053743a3afaa28087eca953b75a433237d43a90468daabf49c5cf539e653721145958fe366bb

test:
  secret_key_base: 74145c9e4f9219b6b7c8e2481bd964c5d86f662aae35a3f0ec02d3e295ee29289cd513866699dc865c457f677deed1b31ee85e274e6e852bc60bf59ffc5542af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
